name: Quote-App-Pipeline

on:
  workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create PEM
        run: |
          echo "${{ secrets.Vani }}" > key.pem
          chmod 400 key.pem

      - name: Copy files
        run: |
          scp -o StrictHostKeyChecking=no -i shri-6.key.pem app.py ec2-user@54.87.139.42:/home/ec2-user/
          scp -o StrictHostKeyChecking=no -i shri-6.key.pem requirements.txt ec2-user@54.87.139.42:/home/ec2-user/
          scp -o StrictHostKeyChecking=no -i shri-6.key.pem Dockerfile ec2-user@54.87.139.42:/home/ec2-user/

      - name: Deploy Docker
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@<your-ip> "
          sudo docker stop quote-app || true &&
          sudo docker rm quote-app || true &&
          sudo docker build -t quote-app /home/ec2-user &&
          sudo docker run -d -p 5010:5000 --name quote-app quote-app
          "
