name: cloudchasers-pipeline
on: workflow_dispatch

jobs:
  build-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v6
        with:
          ref: main

      - name: get pem file
        run: |
          echo "${{secrets.secret_key}}" > Cloudchasers-7key.pem
          chmod 400 Cloudchasers-7key.pem
          ls -lrsth
      - name: cp app.py
        run: scp -o StrictHostKeyChecking=no -i Cloudchasers-7key.pem app.py ec2-user@13.206.123.10:/home/ec2-user/
      - name: cp req.txt
        run: scp -o StrictHostKeyChecking=no -i Cloudchasers-7key.pem requirements.txt ec2-user@13.206.123.10:/home/ec2-user/ 
      - name: run app
        run: ssh -o StrictHostKeyChecking=no -i Cloudchasers-7key.pem ec2-user@13.206.123.10 "cd /home/ec2-user && python3 -m venv venv && source venv/bin/activate && pip3 install -r requirements.txt && python3 app.py"
